name: Build and Push Multiple to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # Wajib untuk push ke GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/stevia:latest
          ghcr.io/${{ github.repository_owner }}/gulaaren:latest
          ghcr.io/${{ github.repository_owner }}/fasting:latest
          ghcr.io/${{ github.repository_owner }}/laori:latest
          ghcr.io/${{ github.repository_owner }}/cortisol:latest
          ghcr.io/${{ github.repository_owner }}/permen:latest
          ghcr.io/${{ github.repository_owner }}/ulangulang:latest
          ghcr.io/${{ github.repository_owner }}/bentarbentar:latest
          ghcr.io/${{ github.repository_owner }}/ultah:latest
          ghcr.io/${{ github.repository_owner }}/ucapindong:latest
